apiVersion: apps/v1
kind: Deployment
metadata:
  name: attack-api
  namespace: observability-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attack-api
  template:
    metadata:
      labels:
        app: attack-api
    spec:
      containers:
        - name: attack-api
          image: attack-api:lastest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path:
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
