apiVersion: v1
kind: Service
metadata:
  name: attack-api
  namespace: observability-demo
  labels:
    app: attack-api

spec:
  selector:
    app: attack-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
