grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin       # change en prod
  service:
    type: NodePort

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    config:
      global: {}
      route:
        receiver: "webhook_default"
      receivers:
        - name: "webhook_default"
          webhook_configs:
            - url: "http://alert-api-svc.monitoring.svc.cluster.local:80/alert"
              send_resolved: true

# Optional: expose Prometheus via NodePort to access locally
prometheusOperator:
  enabled: true
